"""
estimator.py
------------
Estimates token usage for a task based on average input/output word counts.

Core rule (per spec):
    tokens = words * 1.33

Input overhead multiplier by task type (accounts for system prompts, retrieved
context, chat history, etc. that the user doesn't count in "input words"):
    chatbot / RAG     -> 3.0x   (system prompt + retrieved docs + history)
    code generation   -> 1.5x   (file context, instructions, examples)
    everything else   -> 1.1x   (small fixed prompt overhead)

Public function:
    estimate_tokens(task_type, avg_input_words, avg_output_words) -> dict
        returns {"input_tokens": int, "output_tokens": int, "notes": str}

Bonus helper (uses tiktoken when real sample text is available):
    count_tokens_from_text(text, encoding="cl100k_base") -> int
"""

WORDS_TO_TOKENS = 1.33

# Input-side overhead multipliers keyed by canonical task type.
_INPUT_OVERHEAD = {
    "chatbot / RAG": 3.0,
    "code generation": 1.5,
}
_DEFAULT_OVERHEAD = 1.1


def estimate_tokens(task_type: str, avg_input_words: int, avg_output_words: int) -> dict:
    """
    Estimate input/output tokens for one request.

    Args:
        task_type:        one of the canonical TASK_TYPES (used to pick overhead)
        avg_input_words:  average words sent to the model per request
        avg_output_words: average words generated by the model per request

    Returns:
        {"input_tokens": int, "output_tokens": int, "notes": str}
    """
    # Guard against negative / None inputs.
    avg_input_words = max(0, int(avg_input_words or 0))
    avg_output_words = max(0, int(avg_output_words or 0))

    overhead = _INPUT_OVERHEAD.get(task_type, _DEFAULT_OVERHEAD)

    input_tokens = round(avg_input_words * WORDS_TO_TOKENS * overhead)
    output_tokens = round(avg_output_words * WORDS_TO_TOKENS)

    notes = (
        f"Estimated using {WORDS_TO_TOKENS} tokens/word with a {overhead:g}x "
        f"input overhead for '{task_type}'. "
    )
    if overhead == 3.0:
        notes += "RAG/chat adds system prompt, retrieved context, and history."
    elif overhead == 1.5:
        notes += "Code tasks add file context and instructions."
    else:
        notes += "Standard prompt overhead applied."

    return {
        "input_tokens": int(input_tokens),
        "output_tokens": int(output_tokens),
        "notes": notes,
    }


def count_tokens_from_text(text: str, encoding: str = "cl100k_base") -> int:
    """
    Bonus: count tokens in real text precisely using tiktoken.

    Useful when a user can paste an actual sample prompt instead of guessing a
    word count. Falls back to the word-ratio rule if tiktoken is unavailable.
    """
    text = text or ""
    try:
        import tiktoken
        enc = tiktoken.get_encoding(encoding)
        return len(enc.encode(text))
    except Exception:
        # Fallback: approximate from word count.
        return round(len(text.split()) * WORDS_TO_TOKENS)
